# Generated by Django 2.0.5 on 2018-05-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_invoice_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='settingsapp',
            name='icon_color',
        ),
        migrations.RemoveField(
            model_name='settingsapp',
            name='icon_size',
        ),
        migrations.AddField(
            model_name='client',
            name='icon_color',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark'), ('muted', 'Muted'), ('white', 'White')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='icon_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Font Awesome Icon'),
        ),
        migrations.AddField(
            model_name='client',
            name='icon_size',
            field=models.CharField(blank=True, choices=[('1x', 'Small'), ('2x', 'Medium'), ('3x', 'Large'), ('4x', 'XL'), ('5x', 'XXL')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='icon_color',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark'), ('muted', 'Muted'), ('white', 'White')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='icon_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Font Awesome Icon'),
        ),
        migrations.AddField(
            model_name='contact',
            name='icon_size',
            field=models.CharField(blank=True, choices=[('1x', 'Small'), ('2x', 'Medium'), ('3x', 'Large'), ('4x', 'XL'), ('5x', 'XXL')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='icon_color',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark'), ('muted', 'Muted'), ('white', 'White')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='icon_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Font Awesome Icon'),
        ),
        migrations.AddField(
            model_name='contract',
            name='icon_size',
            field=models.CharField(blank=True, choices=[('1x', 'Small'), ('2x', 'Medium'), ('3x', 'Large'), ('4x', 'XL'), ('5x', 'XXL')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='elevation',
            name='icon_color',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark'), ('muted', 'Muted'), ('white', 'White')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='elevation',
            name='icon_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Font Awesome Icon'),
        ),
        migrations.AddField(
            model_name='elevation',
            name='icon_size',
            field=models.CharField(blank=True, choices=[('1x', 'Small'), ('2x', 'Medium'), ('3x', 'Large'), ('4x', 'XL'), ('5x', 'XXL')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='icon_color',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark'), ('muted', 'Muted'), ('white', 'White')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='icon_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Font Awesome Icon'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='icon_size',
            field=models.CharField(blank=True, choices=[('1x', 'Small'), ('2x', 'Medium'), ('3x', 'Large'), ('4x', 'XL'), ('5x', 'XXL')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='icon_color',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark'), ('muted', 'Muted'), ('white', 'White')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='icon_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Font Awesome Icon'),
        ),
        migrations.AddField(
            model_name='file',
            name='icon_size',
            field=models.CharField(blank=True, choices=[('1x', 'Small'), ('2x', 'Medium'), ('3x', 'Large'), ('4x', 'XL'), ('5x', 'XXL')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='icon_color',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark'), ('muted', 'Muted'), ('white', 'White')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='icon_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Font Awesome Icon'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='icon_size',
            field=models.CharField(blank=True, choices=[('1x', 'Small'), ('2x', 'Medium'), ('3x', 'Large'), ('4x', 'XL'), ('5x', 'XXL')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='icon_color',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark'), ('muted', 'Muted'), ('white', 'White')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='icon_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Font Awesome Icon'),
        ),
        migrations.AddField(
            model_name='location',
            name='icon_size',
            field=models.CharField(blank=True, choices=[('1x', 'Small'), ('2x', 'Medium'), ('3x', 'Large'), ('4x', 'XL'), ('5x', 'XXL')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='icon_color',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark'), ('muted', 'Muted'), ('white', 'White')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='icon_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Font Awesome Icon'),
        ),
        migrations.AddField(
            model_name='log',
            name='icon_size',
            field=models.CharField(blank=True, choices=[('1x', 'Small'), ('2x', 'Medium'), ('3x', 'Large'), ('4x', 'XL'), ('5x', 'XXL')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='icon_color',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark'), ('muted', 'Muted'), ('white', 'White')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='icon_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Font Awesome Icon'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='icon_size',
            field=models.CharField(blank=True, choices=[('1x', 'Small'), ('2x', 'Medium'), ('3x', 'Large'), ('4x', 'XL'), ('5x', 'XXL')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='icon_color',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark'), ('muted', 'Muted'), ('white', 'White')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='icon_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Font Awesome Icon'),
        ),
        migrations.AddField(
            model_name='note',
            name='icon_size',
            field=models.CharField(blank=True, choices=[('1x', 'Small'), ('2x', 'Medium'), ('3x', 'Large'), ('4x', 'XL'), ('5x', 'XXL')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='icon_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Font Awesome Icon'),
        ),
        migrations.AddField(
            model_name='project',
            name='icon_color',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark'), ('muted', 'Muted'), ('white', 'White')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='icon_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Font Awesome Icon'),
        ),
        migrations.AddField(
            model_name='project',
            name='icon_size',
            field=models.CharField(blank=True, choices=[('1x', 'Small'), ('2x', 'Medium'), ('3x', 'Large'), ('4x', 'XL'), ('5x', 'XXL')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='icon_color',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark'), ('muted', 'Muted'), ('white', 'White')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='icon_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Font Awesome Icon'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='icon_size',
            field=models.CharField(blank=True, choices=[('1x', 'Small'), ('2x', 'Medium'), ('3x', 'Large'), ('4x', 'XL'), ('5x', 'XXL')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='icon_color',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark'), ('muted', 'Muted'), ('white', 'White')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='icon_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Font Awesome Icon'),
        ),
        migrations.AddField(
            model_name='report',
            name='icon_size',
            field=models.CharField(blank=True, choices=[('1x', 'Small'), ('2x', 'Medium'), ('3x', 'Large'), ('4x', 'XL'), ('5x', 'XXL')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='icon_color',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark'), ('muted', 'Muted'), ('white', 'White')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='icon_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Font Awesome Icon'),
        ),
        migrations.AddField(
            model_name='service',
            name='icon_size',
            field=models.CharField(blank=True, choices=[('1x', 'Small'), ('2x', 'Medium'), ('3x', 'Large'), ('4x', 'XL'), ('5x', 'XXL')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='icon_color',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark'), ('muted', 'Muted'), ('white', 'White')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='icon_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Font Awesome Icon'),
        ),
        migrations.AddField(
            model_name='task',
            name='icon_size',
            field=models.CharField(blank=True, choices=[('1x', 'Small'), ('2x', 'Medium'), ('3x', 'Large'), ('4x', 'XL'), ('5x', 'XXL')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='icon_color',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark'), ('muted', 'Muted'), ('white', 'White')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='icon_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Font Awesome Icon'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='icon_size',
            field=models.CharField(blank=True, choices=[('1x', 'Small'), ('2x', 'Medium'), ('3x', 'Large'), ('4x', 'XL'), ('5x', 'XXL')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='icon_color',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark'), ('muted', 'Muted'), ('white', 'White')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='icon_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Font Awesome Icon'),
        ),
        migrations.AddField(
            model_name='time',
            name='icon_size',
            field=models.CharField(blank=True, choices=[('1x', 'Small'), ('2x', 'Medium'), ('3x', 'Large'), ('4x', 'XL'), ('5x', 'XXL')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='zipcode',
            name='icon_color',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark'), ('muted', 'Muted'), ('white', 'White')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='zipcode',
            name='icon_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Font Awesome Icon'),
        ),
        migrations.AddField(
            model_name='zipcode',
            name='icon_size',
            field=models.CharField(blank=True, choices=[('1x', 'Small'), ('2x', 'Medium'), ('3x', 'Large'), ('4x', 'XL'), ('5x', 'XXL')], max_length=255, null=True),
        ),
    ]
