# Generated by Django 2.0.5 on 2018-05-24 23:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_auto_20180516_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dashboard_items',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('times', 'Times')], max_length=5, null=True, verbose_name='Dashboard Items'),
        ),
    ]
