# Generated by Django 2.0.5 on 2018-05-30 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_auto_20180524_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='preferred_payment_method',
            new_name='payment_method',
        ),
    ]
