# Generated by Django 2.0.6 on 2018-06-23 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_auto_20180623_1950'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SettingsContract',
        ),
    ]
