# Generated by Django 2.0.6 on 2018-06-25 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_delete_settingscontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='task',
            field=models.ForeignKey(blank=True, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Task'),
        ),
    ]
