# Generated by Django 2.0.6 on 2018-06-25 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_estimate_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Start Date'),
        ),
    ]
